include::config/asciidoc.cfg[]
:toc-title: Documentation

= Documentation

== xref:getting-started.adoc[Getting Started]

If you want to know where to start and how to get used to it.

== xref:examples.adoc[Examples]

If you want to know how to use it.

== xref:api-reference.adoc[API Reference]

If you need to know the specific details of the public API

== xref:architecture.adoc[Architecture]

If you want to know the architecture in general and the decisions which led to it.

== xref:development-environment.adoc[Development Environment Setup]

If you want to know how to set up your system for development

== xref:ci-cd-environment.adoc[Continuos Integration / Continuos Deployment]

If you want to know how CI / CD is organized

== xref:Contribution.adoc[Contribution]

If you want to know how to contribute code, fix bugs and make pull requests


[plantuml, target=documentation-workflow, format=svg, id="contribution"]
....
include::config/plantuml.cfg[]
start

if (Know Alredy Everything?) then (yes)
  :Contribute;

  if (All fine?) then (yes)
    :Read the Documentation;
    :Contribute;
  else (no)

  endif

else (no)
:Read the Documentation;
endif

stop
....
